### ISSUE TITLE
Montar documentação de todos os serviços do backend

### ISSUE THREAD

**Issue by V-Perotto** [gwebeer/liveasy-back#8]
# Task
Seguir o exemplo do [link](https://bacen.github.io/pix-api/index.html) (Swagger).

- [x] Buscar os serviços do Back para documentar.
- [x] Criar a documentação:
    - [x] Melhorar descrição:
        - [x] Documentar as Controllers;
    - [x] Melhorar retornos das funções.

# Dúvidas
- Foram sanadas (atribuição do Swagger).

**Comment by V-Perotto** [comment]
Invés de utilizar /{key}/{value} na rota de PUT, use somente /{id} e adicione o JSON para ser editado, será melhor.
